name: "CI"
on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    # Run every Friday at 00:00 UTC
    - cron: "0 0 * * 5"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
      - name: Cache pre-commit hooks
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks on all files
        run: pre-commit run --all-files

  nix-build-check:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Build nix package
        run: nix build --profile default
        # use --profile default to avoid dependencies being gc

      - name: Run nix flake check
        run: nix flake check --all-systems

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Run integration tests with coverage
        run: run-cov -- --show-output

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: github.actor != 'dependabot[bot]'
